//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Admin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_account
    {
        public bank_account()
        {
            this.transaction_bank = new HashSet<transaction_bank>();
            this.transaction_bankSMS = new HashSet<transaction_bankSMS>();
            this.transaction_game = new HashSet<transaction_game>();
            this.transaction_game1 = new HashSet<transaction_game>();
        }
    
        public long id { get; set; }
        public long bank_id { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string link { get; set; }
        public string account_number { get; set; }
        public string bank_account_name { get; set; }
        public string bank_password { get; set; }
        public Nullable<long> user_id { get; set; }
        public bool visible { get; set; }
    
        public virtual bank bank { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<transaction_bank> transaction_bank { get; set; }
        public virtual ICollection<transaction_bankSMS> transaction_bankSMS { get; set; }
        public virtual ICollection<transaction_game> transaction_game { get; set; }
        public virtual ICollection<transaction_game> transaction_game1 { get; set; }
    }
}
