//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Admin.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaymentEntities : DbContext
    {
        public PaymentEntities()
            : base("name=PaymentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bank> banks { get; set; }
        public DbSet<bank_account> bank_account { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<session> sessions { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<transaction_bank> transaction_bank { get; set; }
        public DbSet<transaction_bankSMS> transaction_bankSMS { get; set; }
        public DbSet<transaction_game> transaction_game { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<user_role> user_role { get; set; }
    }
}
