//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Admin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public int failed_login_count { get; set; }
        public string note { get; set; }
        public System.DateTime created_date { get; set; }
        public string body_query_content { get; set; }
        public string ip { get; set; }
    
        public virtual user user { get; set; }
    }
}
