//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Admin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_game
    {
        public long id { get; set; }
        public string recived_account { get; set; }
        public string sent_account { get; set; }
        public decimal amount { get; set; }
        public string note { get; set; }
        public int status { get; set; }
        public string date_trans { get; set; }
        public System.DateTime created_date { get; set; }
        public long recived_bank_id { get; set; }
        public long sent_bank_id { get; set; }
    
        public virtual bank_account bank_account { get; set; }
        public virtual bank_account bank_account1 { get; set; }
    }
}
