//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.Admin.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public user()
        {
            this.bank_account = new HashSet<bank_account>();
            this.sessions = new HashSet<session>();
        }

        [Required]
        public string user_name { get; set; }
        public long id { get; set; }
        public string number_phone { get; set; }
        public string fullname { get; set; }
        public string note { get; set; }
        public Nullable<int> status { get; set; }
        [Required]
        public string pass { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public string last_login_ip { get; set; }
    
        public virtual ICollection<bank_account> bank_account { get; set; }
        public virtual ICollection<session> sessions { get; set; }
    }
}
